apiVersion: apps/v1
kind: Deployment
metadata:
  name: argghf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argghf
  template:
    metadata:
      labels:
        app: argghf
    spec:
      containers:
      - image: okteto.dev/argghf:latest
        name: argghf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1a22c07d-9102-410a-b4ff-1f5e42a7effe"
        - name: Vless_Path
          value: "/vl55reterg454"
        - name: Vmess_UUID
          value: "1a22c07d-9102-410a-b4ff-1f5e42a7effe"
        - name: Vmess_Path
          value: "/vm665erte5ye"
        - name: Share_Path
          value: "/v2link"
